# docker-compose.yml
version: "3"
services:
  odindex:
    image: quericy/odindex-docker
    environment:
    - REFRESH_TOKEN=
    - CLIENT_ID=
    - CLIENT_SECRET=
    - SITE_PATH=
    - OPEN_REWRITE=false
    - USE_PROXY=true
    volumes:
    - ./config:/var/www/html/config
